app/routes.py
from flask import Blueprint, Response, render_template, send_file
import rollbar
from varsnap import varsnap

from app import cache, chasecenter, ical, oraclepark

handlers = Blueprint('handlers', __name__)


@handlers.route("/")
def index() -> str:
    return render_template("index.htm")


@handlers.route("/ical_view")
def ical_view() -> str:
    return render_template("ical_view.htm")


@handlers.route("/chase_center")
def chase_center() -> bytes:
    cached_page = cache.read_raw_cache(cache.CACHED_CHASECENTER_HTML)
    if not cached_page:
        events = chasecenter.get_events()
        events = [e for e in events if e.is_future]
        if len(events) == 0:
            rollbar.report_message('Chasecenter no events', 'error')
        page = render_template("chase_center.htm", events=events).encode('utf-8')
        cache.save_raw_cache(cache.CACHED_CHASECENTER_HTML, page)
    else:
        page = cached_page
    return page


@handlers.route("/chasecenter.ics")
def ical_file() -> Response:
    cached_file = cache.read_raw_cache(cache.CACHED_CHASECENTER_ICS)
    if not cached_file:
        events = chasecenter.get_events()
        if len(events) == 0:
            rollbar.report_message('Chasecenter no events', 'error')
        cal = ical.generate_calendar(events, 'Chase Center')
        cache.save_raw_cache(cache.CACHED_CHASECENTER_ICS, cal)
    return send_file(
        cache.get_cache_file(cache.CACHED_CHASECENTER_ICS),
        mimetype="text/calendar",
        as_attachment=True,
        download_name="chasecenter.ics",
    )


@handlers.route("/oracle_park")
def oracle_park() -> bytes:
    cached_page = cache.read_raw_cache(cache.CACHED_ORACLEPARK_HTML)
    if not cached_page:
        events = oraclepark.get_events()
        events = [e for e in events if e.is_future]
        if len(events) == 0:
            rollbar.report_message('Oracle Park no events', 'error')
        page = render_template("oracle_park.htm", events=events).encode('utf-8')
        cache.save_raw_cache(cache.CACHED_ORACLEPARK_HTML, page)
    else:
        page = cached_page
    return page


@handlers.route("/oraclepark.ics")
def oracle_park_ics_file() -> Response:
    cached_file = cache.read_raw_cache(cache.CACHED_ORACLEPARK_ICS)
    if not cached_file:
        events = oraclepark.get_events()
        if len(events) == 0:
            rollbar.report_message('Oracle Park no events', 'error')
        cal = ical.generate_calendar(events, 'Oracle Park')
        cache.save_raw_cache(cache.CACHED_ORACLEPARK_ICS, cal)
    return send_file(
        cache.get_cache_file(cache.CACHED_ORACLEPARK_ICS),
        mimetype="text/calendar",
        as_attachment=True,
        download_name="oraclepark.ics",
    )


@handlers.route("/about")
@varsnap
def about() -> str:
    return render_template("about.htm")

app/templates/404.htm
{% extends "includes/base.htm" %}
{% block title %}Page Not Found - Chase Center Calendar{% endblock %}
{% block head %}
  {{ super() }}
{% endblock %}
{% block content %}
  Page Not Found
{% endblock %}

app/templates/about.htm
{% extends "includes/base.htm" %}
{% block title %}About - Chase Center Calendar{% endblock %}
{% block head %}
  {{ super() }}
{% endblock %}
{% block content %}
  <h1>
    About Chase Center Calendar
  </h1>
  <div>
    <p>
      I started this website to track events at the San Francisco Chase Center.
      Although I have no interest in attending Chase Center events, I work in
      the area and need to be aware of events that may impact my commute.
      Although farther away, Oracle Park also has many events that bring a lot
      of traffic to the area.
    </p>
    <p>
      Data for Chase Center events are from <a href="https://chasecenter.com">chasecenter.com</a>.<br />
      Data for Oracle Park events are from <a href="https://dothebay.com/venues/oracle-park/events">DoTheBay</a> and <a href="https://www.mlb.com/giants/schedule/">MLB</a>.<br />
      Calendar embedding is from <a href="https://calendar.google.com/">Google Calendar</a>.
    </p>
    <p>
      This website has no relationship with the <a href="https://chasecenter.com/">San Francisco Chase Center</a>,
      <a href="https://www.mlb.com/giants/ballpark">Oracle Park</a>, <a href="https://dothebay.com/">DoTheBay</a>,
      nor  <a href="https://www.uber.com/">Uber</a>.  All trademarks are property of their respective owners.
    </p>
    <p>
      Contribute to this website on <a href="https://github.com/albertyw/chase-center-calendar">Github</a>.
    </p>
    <p id="logos">
      <img src="{{ url_for('static', filename='img/chase.png') }}" />
      <img src="{{ url_for('static', filename='img/oracle.png') }}" />
      <img src="{{ url_for('static', filename='img/uber.png') }}" />
    </p>
  </div>
{% endblock %}

app/templates/chase_center.htm
{% extends "includes/base.htm" %}
{% block title %}Chase Center Calendar - Chase Center{% endblock %}
{% block head %}
  {{ super() }}
{% endblock %}
{% block content %}
  <div>
    <h1>Chase Center Calendar</h1>
    <div id="events">
      {% for event in events %}
        <div class="event">
          <h2>{{ event.title }}</h2>
          <h3>{{ event.date.strftime('%A %Y-%m-%d') }} {{ event.date.strftime('%I:%M %p') }} - {{ event.end.strftime('%I:%M %p') }}</h3>
          {% if event.subtitle %}
            {{ event.subtitle }}<br />
          {% endif %}
          {% if event.location_name %}
            {{ event.location_name }}<br />
          {% endif %}
          {% if event.location_type %}
            {{ event.location_type }}<br />
          {% endif %}
        </div>
      {% else %}
        <p>No upcoming events.</p>
      {% endfor %}
    </div>
  </div>
{% endblock %}

app/templates/ical_view.htm
{% extends "includes/base.htm" %}
{% block title %}iCal - Chase Center Calendar{% endblock %}
{% block head %}
  {{ super() }}
{% endblock %}
{% block content %}
  <div>
    <h1>iCalendar</h1>
    <div id="info">
      <p>
        The calendar is available in the iCal format so it can be loaded into Google Calendar, Apple Calendar, etc.
      </p>
      <h2>Chase Center</h2>
      <p>
        Import this URL into your calendar app for Chase Center events:
        <pre>{{ url_for('handlers.ical_file', _external=True) }}</pre>
      </p>
      <p>
        Alternatively, you can download the calendar but you will not be able to automatically synchronize updates:<br />
        <a href="{{ url_for('handlers.ical_file') }}">Download Chase Center Non-Synchronized Calendar</a>
      </p>
      <h2>Oracle Park</h2>
      <p>
        Import this URL into your calendar app for Oracle Park events:
        <pre>{{ url_for('handlers.oracle_park_ics_file', _external=True) }}</pre>
      </p>
      <p>
        Alternatively, you can download the calendar but you will not be able to automatically synchronize updates:<br />
        <a href="{{ url_for('handlers.oracle_park_ics_file') }}">Download Oracle Park Non-Synchronized Calendar</a>
      </p>
    </div>
  </div>
{% endblock %}

app/templates/includes/base.htm
<!doctype html>
<html lang="en">
  <head>
    {% block head %}
    {# Language #}
    <meta charset="utf-8">
    <meta name="Description" content="Track events at the San Francisco Chase Center">
    <title>{% block title %}{% endblock %}</title>

    {# Style #}
    <meta name="theme-color" content="#ffffff">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{{ url_for('static', filename='gen/main.css') }}" />

    {# Favicon #}
    <link rel="shortcut icon" href="/static/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/static/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='img/favicon/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='img/favicon/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='img/favicon/favicon-16x16.png') }}">
    <link rel="manifest" href="{{ url_for('static', filename='img/favicon/manifest.json') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon/favicon.ico') }}">

    {# Facebook Meta Tags #}
    <meta property="og:url" content="https://www.chasecentercalendar.com/">
    <meta property="og:type" content="website">
    <meta property="og:title" content="Chase Center Calendar">
    <meta property="og:description" content="Track events at the San Francisco Chase Center">
    <meta property="og:image" content="https://www.chasecentercalendar.com/static/img/favicon/android-chrome-512x512.png">

    {# Twitter Meta Tags #}
    <meta name="twitter:card" content="summary">
    <meta property="twitter:domain" content="chasecentercalendar.com">
    <meta property="twitter:url" content="https://www.chasecentercalendar.com/">
    <meta name="twitter:title" content="Chase Center Calendar">
    <meta name="twitter:description" content="Track events at the San Francisco Chase Center">
    <meta name="twitter:image" content="https://www.chasecentercalendar.com/static/img/favicon/android-chrome-512x512.png">

    {# External Dependencies #}
    <meta name="google-site-verification" content="" />
    <link rel="preconnect" href="https://www.google-analytics.com">
    <link rel="preconnect" href="https://www.googletagmanager.com">
    <link rel="preconnect" href="https://ingest.log.fit">
    <link rel="preconnect" href="https://www.varsnap.com">

    {# Miscellaneous #}
    <link type="text/plain" rel="author" href="{{ url_for('humans', _external=True) }}" />
    {% endblock %}
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand mb-0 h1" href="/">Chase Center Calendar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="navbar-nav me-auto mb-2 mb-lg-0">
              <a class="nav-item nav-link" aria-current="page" href="/">Home</a>
              <a class="nav-item nav-link" aria-current="page" href="{{ url_for('handlers.chase_center') }}">Chase Center</a>
              <a class="nav-item nav-link" aria-current="page" href="{{ url_for('handlers.oracle_park') }}">Oracle Park</a>
              <a class="nav-item nav-link" aria-current="page" href="{{ url_for('handlers.ical_view') }}">iCal</a>
              <a class="nav-item nav-link" aria-current="page" href="{{ url_for('handlers.about') }}">About</a>
            </div>
          </div>
        </div>
      </nav>
      <div id="main">
        {% block content %}{% endblock %}
      </div>
      <footer id="footer">
        {% block footer %}
          &copy; by <a href="https://www.albertyw.com/">Albert Wang</a>.
        {% endblock %}
      </footer>
    </div>
    <script src="{{ url_for('static', filename='gen/main.js') }}"></script>
  </body>
</html>

app/templates/index.htm
{% extends "includes/base.htm" %}
{% block title %}Chase Center Calendar{% endblock %}
{% block head %}
  {{ super() }}
{% endblock %}
{% block content %}
  <div>
    <h1>Chase Center Calendar</h1>
    <div class="embed-calendar">
      <iframe src="https://calendar.google.com/calendar/u/0/embed?height=600&wkst=1&ctz=America/Los_Angeles&mode=AGENDA&title=Chase+Center+Calendar&showCalendars=0&src=aTVuYzU1ZGNxZnBuc3B0dWVqMG5jbGRvNGpnb3RxdTBAaW1wb3J0LmNhbGVuZGFyLmdvb2dsZS5jb20&color=%23F4511E" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
    </div>
    <h1>Oracle Park Calendar</h1>
    <div class="embed-calendar">
      <iframe src="https://calendar.google.com/calendar/u/0/embed?height=600&wkst=1&ctz=America/Los_Angeles&mode=AGENDA&title=Oracle+Park+Calendar&showCalendars=0&src=bDg3Y25wN2QyYzhwcjk1amE5MWo5a25jZzMxNDQyM3NAaW1wb3J0LmNhbGVuZGFyLmdvb2dsZS5jb20&color=%23F4511E" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
    </div>
  </div>
{% endblock %}

app/templates/oracle_park.htm
{% extends "includes/base.htm" %}
{% block title %}Chase Center Calendar - Oracle Park{% endblock %}
{% block head %}
  {{ super() }}
{% endblock %}
{% block content %}
  <div>
    <h1>Oracle Park Calendar</h1>
    {#
      <iframe src="https://calendar.google.com/calendar/u/0/embed?height=600&wkst=1&ctz=America/Los_Angeles&mode=AGENDA&title=Oracle+Park+Calendar&showCalendars=0&src=bDg3Y25wN2QyYzhwcjk1amE5MWo5a25jZzMxNDQyM3NAaW1wb3J0LmNhbGVuZGFyLmdvb2dsZS5jb20&color=%23F4511E" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
    #}
    <div id="events">
      {% for event in events %}
        <div class="event">
          <h2>{{ event.title }}</h2>
          <h3>{{ event.date.strftime('%A %Y-%m-%d') }} {{ event.date.strftime('%I:%M %p') }} - {{ event.end.strftime('%I:%M %p') }}</h3>
          {% if event.subtitle %}
            {{ event.subtitle }}<br />
          {% endif %}
          {% if event.location_name %}
            {{ event.location_name }}<br />
          {% endif %}
          {% if event.location_type %}
            {{ event.location_type }}<br />
          {% endif %}
        </div>
      {% else %}
        <p>No upcoming events.</p>
      {% endfor %}
    </div>
  </div>
{% endblock %}